### ISSUE TITLE
Problem with NavigationToolbar2TkAgg

### ISSUE THREAD

**Issue by nluetzge** [spacetelescope/jwst_coronagraph_visibility#34]
I'm trying to run the tool when installing it through astroconda and I'm getting this traceback:

```
(astroconda) Linus:~ nluetzge$ Traceback (most recent call last):
  File "/anaconda3/envs/astroconda/bin/jwst-coronagraph-visibility-gui", line 11, in <module>
    load_entry_point('jwst-coronagraph-visibility==0.1.0', 'gui_scripts', 'jwst-coronagraph-visibility-gui')()
  File "/anaconda3/envs/astroconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/anaconda3/envs/astroconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/anaconda3/envs/astroconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/anaconda3/envs/astroconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/anaconda3/envs/astroconda/lib/python3.6/site-packages/jwst_coronagraph_visibility/gui.py", line 29, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
ImportError: cannot import name 'NavigationToolbar2TkAgg'

```

Some googling told me that apparently `NavigationToolbar2TkAgg` has changed name to `NavigationToolbar2QT` could somebody fix this? 

Cheers, 
Nora

**Comment by juliengirard** [comment]
Hi Nora,
Brendan has fixed the conda one, could you please try:
`conda install jwst_coronagraph_visibility=0.4.2`

`pip install jwst_coronagraph_visibility`

They both work on my laptop, at least on a clean 3.6 environment.
Cheers,
Julien

**Comment by nluetzge** [comment]
Thanks! I already communicated with Brendan and I can confirm that the 0.4.2 version works.
